-- Internal support tickets raised from the admin Support panel. Admin-only:
-- staff create, read and update tickets (no public/customer access). `number`
-- is a KZN-#### reference — randomly generated by the app but UNIQUE here, so a
-- collision is rejected and the app retries. An optional screenshot is stored in
-- the existing public `media` bucket (under a `support/` prefix) and referenced
-- by URL.
create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  number text not null unique,
  title text not null,
  description text not null,
  image_url text,
  status text not null default 'open'
);

create index if not exists support_tickets_created_idx
  on public.support_tickets (created_at desc);

create trigger support_tickets_updated_at before update on public.support_tickets
  for each row execute function public.set_updated_at();

alter table public.support_tickets enable row level security;

create policy "Admins read support tickets"
  on public.support_tickets for select
  using (public.is_admin());
create policy "Admins insert support tickets"
  on public.support_tickets for insert
  with check (public.is_admin());
create policy "Admins update support tickets"
  on public.support_tickets for update
  using (public.is_admin())
  with check (public.is_admin());
